### ISSUE TITLE
Autologin followups

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-mysky#274]
# ISSUE

## Followups

- [ ] this comment applies to all of these test cases, shouldn't we actually assert something instead of just calling the function? We should call something like account.<portal>/api/user in order to confirm the user is logged in or not logged in (403). 

**TODO:** This endpoint is not exposed through CORS. Can't test this yet.
**TODO:** This endpoint doesn't seem to take a pubkey. There isn't currently a way to authenticate in integration tests.

- [ ] Unskip skipped integration test (once the endpoint is working)

_Originally posted by @peterjan in https://github.com/SkynetLabs/skynet-mysky/pull/254#discussion_r821503662_

- [x] So usually you'd do `Promise<PortalAccounts|null>` and then return `null` if the data is not there? This is annoying for your end-user because he'll have to deal with it in weird way.

_Originally posted by @peterjan in https://github.com/SkynetLabs/skynet-mysky/pull/254#discussion_r821505821_

- [x] important? looks like it might be nice to do these TODOs inside this PR, if not let's create an issue for it

_Originally posted by @peterjan in https://github.com/SkynetLabs/skynet-mysky/pull/254#discussion_r821512211_

- [x] `nit` also returns whether the user was logged in

_Originally posted by @peterjan in https://github.com/SkynetLabs/skynet-mysky/pull/254#discussion_r821513149_
